# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/akonadi-search' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kldap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/ktnef' : '@same'
    'pim/libgravatar' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/libksieve' : '@same'
    'pim/mailcommon' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'
    'frameworks/kbookmarks': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kdoctools': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kitemviews': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/kparts': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/sonnet': '@latest'
    'frameworks/ktextwidgets': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'frameworks/kiconthemes': '@latest'
    'third-party/qtkeychain': '@latest'
    'libraries/ktextaddons': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/kcalendarcore' : '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/akonadi-contacts' : '@latest-kf6'
    'pim/akonadi-mime' : '@latest-kf6'
    'pim/akonadi-search' : '@latest-kf6'
    'pim/kcalutils' : '@latest-kf6'
    'pim/kidentitymanagement' : '@latest-kf6'
    'pim/kldap' : '@latest-kf6'
    'pim/kmailtransport' : '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/kontactinterface' : '@latest-kf6'
    'pim/kpimtextedit' : '@latest-kf6'
    'pim/ktnef' : '@latest-kf6'
    'pim/libgravatar' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'
    'pim/libkleo' : '@latest-kf6'
    'pim/libksieve' : '@latest-kf6'
    'pim/mailcommon' : '@latest-kf6'
    'pim/messagelib' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'
    'frameworks/kbookmarks': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/sonnet': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'third-party/qtkeychain': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'
