# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-contacts' : '@same'
    'kde/pim/akonadi-mime' : '@same'
    'kde/pim/akonadi-search' : '@same'
    'kde/pim/kcalutils' : '@same'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kldap' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/kontactinterface' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/ktnef' : '@same'
    'kde/pim/libgravatar' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/libkleo' : '@same'
    'kde/pim/libksieve' : '@same'
    'kde/pim/mailcommon' : '@same'
    'kde/pim/messagelib' : '@same'
    'kde/pim/pimcommon' : '@same'
