# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcontacts' : 'Frameworks/6.24'
    'frameworks/kcalendarcore' : 'Frameworks/6.24'
    'pim/akonadi' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kldap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/ktnef' : '@same'
    'pim/libgravatar' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/libksieve' : '@same'
    'pim/mailcommon' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'
    'frameworks/kbookmarks': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kitemviews': 'Frameworks/6.24'
    'frameworks/kjobwidgets': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/knotifyconfig': 'Frameworks/6.24'
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/sonnet': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kstatusnotifieritem': 'Frameworks/6.24'
    'frameworks/kuserfeedback': 'Frameworks/6.24'
    'third-party/qtkeychain': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/plasma-activities': '@latest-kf6'
    'pim/akonadi-search' : '@same'



Options:
  cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
  require-passing-tests-on: [ '@all' ]
  cppcheck-arguments: '--enable=warning,performance,portability,style,unusedFunction --suppress-xml=cppcheck-suppressions.xml'
