/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a kmailpartadaptor -- org.kde.kmail.kmailpart.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KMAILPARTADAPTOR_H_320651150894158
#define KMAILPARTADAPTOR_H_320651150894158

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kmail.kmailpart
 */
class KmailpartAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kmail.kmailpart")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kmail.kmailpart\" >\n"
"    <method name=\"save\" />\n"
"    <method name=\"exit\" />\n"
"  </interface>\n"
        "")
public:
    KmailpartAdaptor(QObject *parent);
    virtual ~KmailpartAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void exit();
    void save();
Q_SIGNALS: // SIGNALS
};

#endif
