/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a mailcomposeradaptor -- org.kde.kmail.mailcomposer.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MAILCOMPOSERADAPTOR_H_146551150893499
#define MAILCOMPOSERADAPTOR_H_146551150893499

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kmail.mailcomposer
 */
class MailcomposerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kmail.mailcomposer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kmail.mailcomposer\" >\n"
"    <method name=\"send\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"how\" />\n"
"    </method>\n"
"    <method name=\"addAttachment\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"comment\" />\n"
"    </method>\n"
"    <method name=\"setBody\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"body\" />\n"
"    </method>\n"
"    <method name=\"addAttachment\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"cte\" />\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"type\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"subType\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"paramAttr\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"paramValue\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"contDisp\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MailcomposerAdaptor(QObject *parent);
    virtual ~MailcomposerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addAttachment(const QString &name, const QString &cte, const QByteArray &data, const QString &type, const QString &subType, const QString &paramAttr, const QString &paramValue, const QString &contDisp);
    void addAttachment(const QString &url, const QString &comment);
    void send(int how);
    void setBody(const QString &body);
Q_SIGNALS: // SIGNALS
};

#endif
