/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a mailcomposeradaptor -- org.kde.kmail.mailcomposer.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mailcomposeradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MailcomposerAdaptor
 */

MailcomposerAdaptor::MailcomposerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MailcomposerAdaptor::~MailcomposerAdaptor()
{
    // destructor
}

void MailcomposerAdaptor::addAttachment(const QString &name, const QString &cte, const QByteArray &data, const QString &type, const QString &subType, const QString &paramAttr, const QString &paramValue, const QString &contDisp)
{
    // handle method call org.kde.kmail.mailcomposer.addAttachment
    QMetaObject::invokeMethod(parent(), "addAttachment", Q_ARG(QString, name), Q_ARG(QString, cte), Q_ARG(QByteArray, data), Q_ARG(QString, type), Q_ARG(QString, subType), Q_ARG(QString, paramAttr), Q_ARG(QString, paramValue), Q_ARG(QString, contDisp));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->addAttachment(name, cte, data, type, subType, paramAttr, paramValue, contDisp);
}

void MailcomposerAdaptor::addAttachment(const QString &url, const QString &comment)
{
    // handle method call org.kde.kmail.mailcomposer.addAttachment
    QMetaObject::invokeMethod(parent(), "addAttachment", Q_ARG(QString, url), Q_ARG(QString, comment));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->addAttachment(url, comment);
}

void MailcomposerAdaptor::send(int how)
{
    // handle method call org.kde.kmail.mailcomposer.send
    QMetaObject::invokeMethod(parent(), "send", Q_ARG(int, how));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->send(how);
}

void MailcomposerAdaptor::setBody(const QString &body)
{
    // handle method call org.kde.kmail.mailcomposer.setBody
    QMetaObject::invokeMethod(parent(), "setBody", Q_ARG(QString, body));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setBody(body);
}


#include "mailcomposeradaptor.moc"
