select distinct ?r where  { {
      ?r <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#to> ?v1 . 
      ?v1 <http://www.semanticdesktop.org/ontologies/2007/03/22/nco#hasEmailAddress> ?v2 .
      ?v2 <http://www.semanticdesktop.org/ontologies/2007/03/22/nco#emailAddress> "vkrause@kde.org"^^<http://www.w3.org/2001/XMLSchema#string> . 
      ?r a ?v3 . ?v3 <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Email> .
} . }
